### ISSUE TITLE
Errors in requirements.txt

### ISSUE THREAD

**Issue by JasonG-FR** [SupahNoob/energy-usage-analysis#1]
Hi,

I got an error while doing `pip3 install -r requirements.txt`:
```
Invalid requirement: 'pandas=0.22.0'
= is not a valid operator. Did you mean == ?
```
Same for numpy. 

Corrected version of requirements.txt:
```
matplotlib==2.2.2
seaborn==0.8.1
pandas==0.22.0
numpy==1.14.2
```

**Comment by boonhapus** [comment]
D'oh! Thanks for that. It's what I get for hastily adding it at the last second.
